[sample]
secret = "oops"
length = 10

# [THEME]
## Available colors names:
##  DarkGrey Black Red DarkRed Green DarkGreen Yellow DarkYellow
##  Blue DarkBlue Magenta DarkMagenta Cyan DarkCyan White Grey
# name = "White"
# code = "Green"
